In [1]:
import numpy as np
from sklearn.datasets import make_moons, fetch_covtype
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, auc, accuracy_score, confusion_matrix
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline
import matplotlib.pylab as plt
import itertools

In [4]:
!pip uninstall scikit-learn -y
!pip install -U scikit-learn

Found existing installation: scikit-learn 0.22.2.post1
Uninstalling scikit-learn-0.22.2.post1:
  Successfully uninstalled scikit-learn-0.22.2.post1
Collecting scikit-learn
  Downloading scikit_learn-1.0.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (23.2 MB)
     |████████████████████████████████| 23.2 MB 1.6 MB/s
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.4.1)
Requirement already satisfied: numpy>=1.14.6 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.19.5)
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-3.0.0-py3-none-any.whl (14 kB)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.1.0)
Installing collected packages: threadpoolctl, scikit-learn
Successfully installed scikit-learn-1.0.1 threadpoolctl-3.0.0

In [2]:
dataset = fetch_covtype(shuffle=True,as_frame=True) # flag de shuffle activado para que nos entregue los datos ya mezclados
dataframe = dataset.frame
dataframe.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type_31,Soil_Type_32,Soil_Type_33,Soil_Type_34,Soil_Type_35,Soil_Type_36,Soil_Type_37,Soil_Type_38,Soil_Type_39,Cover_Type
0,3213.0,130.0,18.0,216.0,46.0,2663.0,246.0,227.0,102.0,836.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,3184.0,101.0,18.0,696.0,248.0,1434.0,247.0,213.0,88.0,2627.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
2,2833.0,271.0,45.0,300.0,199.0,1401.0,70.0,208.0,252.0,1461.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
3,2675.0,164.0,10.0,120.0,36.0,1999.0,230.0,243.0,145.0,1585.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
4,2885.0,18.0,18.0,268.0,72.0,2730.0,202.0,198.0,128.0,1839.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2

In [3]:
import pandas as pd

df1 = dataframe[dataframe['Cover_Type']==1].sample(n=1000)
df2 = dataframe[dataframe['Cover_Type']==2].sample(n=1000)
df3 = dataframe[dataframe['Cover_Type']==3].sample(n=1000)
df4 = dataframe[dataframe['Cover_Type']==4].sample(n=1000)
df5 = dataframe[dataframe['Cover_Type']==5].sample(n=1000)
df6 = dataframe[dataframe['Cover_Type']==6].sample(n=1000)
df7 = dataframe[dataframe['Cover_Type']==7].sample(n=1000)

df = pd.concat([df1,df2,df3,df4,df5,df6,df7])
df.head()

,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,Horizontal_Distance_To_Fire_Points,...,Soil_Type_31,Soil_Type_32,Soil_Type_33,Soil_Type_34,Soil_Type_35,Soil_Type_36,Soil_Type_37,Soil_Type_38,Soil_Type_39,Cover_Type
100665,3153.0,24.0,5.0,153.0,-4.0,4660.0,217.0,230.0,149.0,1380.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
229232,3121.0,50.0,24.0,459.0,96.0,2160.0,223.0,182.0,81.0,1842.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
184721,3286.0,259.0,28.0,180.0,58.0,600.0,143.0,242.0,231.0,1231.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
66165,3138.0,71.0,12.0,277.0,28.0,2040.0,233.0,216.0,113.0,3159.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
52965,3236.0,30.0,13.0,42.0,9.0,2912.0,216.0,212.0,130.0,2221.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [4]:
X = df.iloc[:,1:54].to_numpy()
Y = df['Cover_Type'].to_numpy()
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size=0.7, stratify=Y)

In [5]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
# transform data
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform (X_test) #ojo que no se hace el fit con los datos de test, solo con los de train

In [6]:
C_value=1.0
classifier = SVC(C=C_value, kernel='rbf', gamma=1.0, probability=True,decision_function_shape='ovr')
classifier.fit(X_train, Y_train)
Y_pred = classifier.predict(X_test)
print(Y_pred)

[5 7 2 ... 6 1 3]

In [7]:

# Confusion Matrix
from sklearn.metrics import confusion_matrix
import seaborn as sn

columns = ['class %s' %(i) for i in np.unique(Y)]

confm = confusion_matrix(Y_test, Y_pred)
df_cm = pd.DataFrame(confm, index=columns, columns=columns)
ax = sn.heatmap(df_cm, cmap='Blues',fmt='.3g', annot=True)
sn.set(rc={'figure.figsize':(16,10)})
ax.set_title('Matriz de confusión',fontsize=30)
ax.set_xlabel('Predict Label',fontsize=20)
ax.set_ylabel('True Label',fontsize=20)

ModuleNotFoundError: No module named 'seaborn'